version: 3
includes:
  main:
    taskfile: ../../Taskfile.examples.yml
    flatten: true
env:
  SOLO_NETWORK_SIZE: 7
  SOLO_NAMESPACE: solo-perf-test
  # SOLO_CHART_VERSION: 0.39.0
  # CONSENSUS_NODE_VERSION: v0.58.0
  VALUES_FLAG: "--values-file {{.USER_WORKING_DIR}}/init-containers-values.yaml"
  SETTINGS_FLAG: "--settings-txt {{.USER_WORKING_DIR}}/settings.txt"
  SOLO_HOME: "/Users/user/.solo-perf-test"
  # LOG4J2_FLAG: "--log4j2-xml {{.USER_WORKING_DIR}}/log4j2.xml"
  # APPLICATION_PROPERTIES_FLAG: "--application-properties {{.USER_WORKING_DIR}}/application.properties"
  # HEDERA_SERVICES_ROOT: "/Users/user/source/hedera-services"
  # LOCAL_BUILD_FLAG: "--local-build-path {{.HEDERA_SERVICES_ROOT}}/hedera-node/data"
