version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 2
    open-pull-requests-limit: 5
    groups:
      github-actions-deps:
        patterns:
          - '*'
  - package-ecosystem: "npm"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 2
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      npm-deps:
        patterns:
          - '*'
