templates:
  - MIRROR_NODE_VERSION
  - BLOCK_NODE_VERSION
  - RELAY_VERSION
  - EXPLORER_VERSION
  - MINIO_OPERATOR_VERSION
  - SOLO_CHEETAH_VERSION
  - SOLO_CONTAINERS_VERSION

images:
  # --- Mirror Node ---
  - name: gcr.io/mirrornode/hedera-mirror-pinger
    version: MIRROR_NODE_VERSION
    source: gcr.io

  - name: gcr.io/mirrornode/hedera-mirror-monitor
    version: MIRROR_NODE_VERSION
    source: gcr.io

  - name: gcr.io/mirrornode/hedera-mirror-rest
    version: MIRROR_NODE_VERSION
    source: gcr.io

  - name: gcr.io/mirrornode/hedera-mirror-web3
    version: MIRROR_NODE_VERSION
    source: gcr.io

  - name: ghcr.io/hiero-ledger/hiero-mirror-node/grpc
    version: MIRROR_NODE_VERSION
    source: ghcr.io

  - name: ghcr.io/hiero-ledger/hiero-mirror-node/importer
    version: MIRROR_NODE_VERSION
    source: ghcr.io

  - name: ghcr.io/hiero-ledger/hiero-mirror-node/rest-java
    version: MIRROR_NODE_VERSION
    source: ghcr.io

  - name: gcr.io/mirrornode/redis-sentinel
    version: 8.2.2
    source: gcr.io

  - name: gcr.io/mirrornode/redis
    version: 8.2.2
    source: gcr.io

  # --- Block Node ---
  - name: ghcr.io/hiero-ledger/hiero-block-node
    version: BLOCK_NODE_VERSION
    source: ghcr.io

  # --- Relay ---
  - name: ghcr.io/hiero-ledger/hiero-json-rpc-relay
    version: RELAY_VERSION
    source: ghcr.io

  # --- Explorer ---
  - name: ghcr.io/hiero-ledger/hiero-mirror-node-explorer/hiero-explorer
    version: EXPLORER_VERSION
    source: ghcr.io

  # --- Minio ---
  - name: quay.io/minio/operator
    version: MINIO_OPERATOR_VERSION
    source: quay.io

  - name: quay.io/minio/minio
    version: RELEASE.2024-08-03T04-33-23Z
    source: quay.io

  - name: quay.io/minio/operator-sidecar
    version: v7.0.1
    source: quay.io

  # ---

  - name: docker.io/bitnami/postgresql
    version: latest
    source: docker.io

  - name: docker.io/bitnamilegacy/postgresql-repmgr
    version: 17.6.0-debian-12-r2
    source: docker.io

  - name: docker.io/curlimages/curl
    version: 8.9.1
    source: docker.io

  - name: docker.io/envoyproxy/envoy
    version: v1.21.1
    source: docker.io

  - name: docker.io/haproxytech/haproxy-alpine
    version: 2.4.25
    source: docker.io

  - name: docker.io/kindest/kindnetd
    version: v20241212-9f82dd49
    source: docker.io

  - name: docker.io/kindest/local-path-helper
    version: v20241212-8ac705d0
    source: docker.io

  - name: docker.io/kindest/local-path-provisioner
    version: v20241212-8ac705d0
    source: docker.io

  - name: docker.io/library/busybox
    version: 1.36.1
    source: docker.io

  - name: docker.io/library/busybox
    version: latest
    source: docker.io

  - name: docker.io/library/ubuntu
    version: noble
    source: docker.io

  - name: docker.io/grafana/alloy
    version: v1.11.3
    source: docker.io

  - name: ghcr.io/hashgraph/solo-cheetah/cheetah
    version: SOLO_CHEETAH_VERSION
    source: ghcr.io

  - name: ghcr.io/hashgraph/solo-containers/debian-s6-java25
    version: SOLO_CONTAINERS_VERSION
    source: ghcr.io

  - name: quay.io/jcmoraisjr/haproxy-ingress
    version: v0.14.5
    source: quay.io
