plugins:
  # Check that markdown is consistent.
  - remark-preset-lint-consistent
  # Few recommended rules.
  - remark-preset-lint-recommended
  # list item indentation should be space
  - - remark-lint-list-item-indent
    - space
