version: 3
includes:
  helper:
    taskfile: ./Taskfile.helper.yml
    flatten: true
env:
  SOLO_NETWORK_SIZE: 2
  SOLO_NAMESPACE: solo-e2e
  SOLO_DEPLOYMENT: solo-deployment
  # SOLO_CHART_VERSION: 0.39.0
  # CONSENSUS_NODE_VERSION: v0.58.0
  HEDERA_SERVICES_ROOT: "/Users/user/source/hedera-services"
  # LOCAL_BUILD_FLAG: "--local-build-path {{.HEDERA_SERVICES_ROOT}}/hedera-node/data"
  # DEBUG_NODE_ALIAS: "node2"
  # SOLO_CHARTS_DIR_FLAG: "-d /Users/user/source/solo-charts/charts"
  # LOAD_BALANCER_FLAG: "--load-balancer"
  # ENABLE_EXPLORER_TLS_FLAG: "--enable-hedera-explorer-tls"
  # TLS_CLUSTER_ISSUER_TYPE_FLAG: "--tls-cluster-issuer-type acme-staging"
  # NETWORK_DEPLOY_EXTRA_FLAGS: "--haproxy-ips node1="
vars:
  cross_env: ./node_modules/.bin/cross-env
  mocha_bin: ./node_modules/.bin/mocha
  c8_bin: ./node_modules/.bin/c8

  test_prefix: "{{ .cross_env }} MOCHA_SUITE_NAME"
  reporter_prefix: "{{ .c8_bin }} --report-dir"
  reporter_options_prefix: --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit

  use_port_forwards: "true"

tasks:
  default:
    silent: true
    desc: install Solo, create a kind cluster, deploy the network, set it up, and start it
    deps:
      - task: "init"
    cmds:
      - echo "This command is meant to deploy a Solo network to a Kind cluster on your local machine, "
      - echo "ctrl-c if this is not what you want to do."
      - sleep 5
      - task: "install"
      - task: "start"

  install:
    desc: create the cluster, solo init, solo cluster create, solo node keys, solo network deploy
    deps:
      - task: "init"
    cmds:
      - task: "cluster:create"
      - task: "solo:init"
      - task: "solo:cluster:setup"
      - task: "solo:keys"
      - task: "solo:deployment:create"
      - task: "solo:network:deploy"

  destroy:
    desc: destroy relay, mirror-node, and network
    deps:
      - task: "init"
    cmds:
      - task: "cluster:destroy"

  solo-test:
    cmds:
      - tsx --no-deprecation --no-warnings solo.ts
  solo:
    cmds:
      - node --no-deprecation --no-warnings dist/solo.js
  check:
    cmds:
      - remark . --quiet --frail && eslint . && tsc && madge --circular src/* && npx typedoc --emit none
  format:
    cmds:
      - remark . --quiet --frail --output && eslint --fix . && tsc && madge --circular src/* && npx typedoc --emit none
  test-setup:
    cmds:
      - ./test/e2e/setup-e2e.sh
  build:
    cmds:
      - rm -Rf dist && tsc && node resources/post-build-script.j

  # TESTING COMMANDS
  test:
    cmds:
      - "{{ .test_prefix }}=\"Unit Tests\" 
        {{ .reporter_prefix }}='coverage/unit' 
        {{ .mocha_bin }} 'test/unit/**/*.ts' 
        {{ .reporter_options_prefix }}"

  test-mathex:
    cmds:
      - "{{ .test_prefix }}=\"MathEx Unit Tests\"
        {{ .reporter_prefix }}='coverage/unit-mathex'
        {{ .mocha_bin }} 'test/unit/**/math_ex*.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-all:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E All Tests\" 
        {{ .reporter_prefix }}='coverage/e2e-all' 
        {{ .mocha_bin }} 'test/e2e/**/*.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-integration:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Integration Tests\"
        {{ .reporter_prefix }}='coverage/e2e-integration'
        {{ .mocha_bin }} 'test/e2e/integration/**/*.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-leases:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Lease Tests\"
        {{ .reporter_prefix }}='coverage/e2e-leases'
        {{ .mocha_bin }} 'test/e2e/integration/core/lease*.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-standard:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Standard Tests\"
        {{ .reporter_prefix }}='coverage/e2e-standard'
        {{ .mocha_bin }} 'test/e2e/**/*.ts'
          --ignore 'test/unit/**/*.ts'
          --ignore 'test/e2e/integration/**/*.ts'
          --ignore 'test/e2e/commands/mirror_node*.ts'
          --ignore 'test/e2e/commands/node*.ts'
          --ignore 'test/e2e/commands/separate_node*.ts'
          --ignore 'test/e2e/commands/relay*.ts'
        {{ .reporter_options_prefix }} --timeout 30000"

  test-e2e-mirror-node:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Mirror Node Tests\"
        {{ .reporter_prefix }}='coverage/e2e-mirror-node'
        {{ .mocha_bin }} 'test/e2e/commands/mirror_node.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-pem-stop:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node PEM Stop Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-pem-stop'
        {{ .mocha_bin }} 'test/e2e/commands/node_pem_stop.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-pem-kill:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node PEM Kill Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-pem-kill'
        {{ .mocha_bin }} 'test/e2e/commands/node_pem_kill.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-local-hedera:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node Local Hedera Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-local-hedera'
        {{ .mocha_bin }} 'test/e2e/commands/node_local_hedera.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-local-ptt:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node Local PTT Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-local-ptt'
        {{ .mocha_bin }} 'test/e2e/commands/node_local_ptt.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-add:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node Add Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-add'
        {{ .mocha_bin }} 'test/e2e/commands/node_add.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-add-local:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node Add Local Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-add-local'
        {{ .mocha_bin }} 'test/e2e/commands/node_add_local.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-add-separate:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node Add - Separate commands Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-add-separate'
        {{ .mocha_bin }} 'test/e2e/commands/separate_node_add.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-update:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node Update Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-update'
        {{ .mocha_bin }} 'test/e2e/commands/node_update.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-update-separate:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node Update - Separate commands Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-update-separate'
        {{ .mocha_bin }} 'test/e2e/commands/separate_node_update.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-delete:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node Delete Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-delete'
        {{ .mocha_bin }} 'test/e2e/commands/node_delete.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-delete-separate:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node Delete - Separate commands Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-delete-separate'
        {{ .mocha_bin }} 'test/e2e/commands/separate_node_delete.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-upgrade:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node Upgrade Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-upgrade'
        {{ .mocha_bin }} 'test/e2e/commands/node_upgrade.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-node-upgrade-separate:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Node Upgrade - Separate commands Tests\"
        {{ .reporter_prefix }}='coverage/e2e-node-upgrade-separate'
        {{ .mocha_bin }} 'test/e2e/commands/separate_node_upgrade.test.ts'
        {{ .reporter_options_prefix }}"

  test-e2e-relay:
    cmds:
      - "{{ .test_prefix }}=\"Mocha E2E Relay Tests\"
        {{ .reporter_prefix }}='coverage/e2e-relay'
        {{ .mocha_bin }} 'test/e2e/commands/relay.test.ts'
        {{ .reporter_options_prefix }}"
