version: 3
includes:
  tests:
    taskfile: ./Taskfile.tests.yml
    flatten: true
vars:
  cross_env: npx cross-env
  mocha_bin: npx mocha
  c8_bin: npx c8

  test_prefix: "{{ .cross_env }} MOCHA_SUITE_NAME"
  reporter_prefix: "{{ .c8_bin }} --report-dir"
  reporter_options_prefix: --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit

env:
  SOLO_NETWORK_SIZE: 1
  SOLO_NAMESPACE: solo-e2e
  SOLO_DEPLOYMENT: solo-deployment
  # SOLO_CHART_VERSION: 0.39.0
  # CONSENSUS_NODE_VERSION: v0.58.0
  HEDERA_SERVICES_ROOT: "/Users/user/source/hiero-consensus-node"
  # LOCAL_BUILD_FLAG: "--local-build-path {{.HEDERA_SERVICES_ROOT}}/hedera-node/data"
  # DEBUG_NODE_ALIAS: "node2"
  # SOLO_CHARTS_DIR_FLAG: "--chart-dir /Users/user/source/solo-charts/charts"
  # LOAD_BALANCER_FLAG: "--load-balancer"
  ENABLE_EXPLORER_TLS_FLAG: "--enable-hedera-explorer-tls"
  TLS_CLUSTER_ISSUER_TYPE_FLAG: "--tls-cluster-issuer-type acme-staging"
  # NETWORK_DEPLOY_EXTRA_FLAGS: "--haproxy-ips node1="
  ENABLE_EXPLORER_INGRESS: "--enable-ingress"
  ENABLE_MIRROR_INGRESS: "--enable-ingress"
  EXPLORER_NAME_SPACE: "explorer-name-space"
  EXPLORER_DEPLOYMENT: "explorer-deployment"
  EXPLORER_CLUSTER_CONTEXT: "kind-solo-cluster"

tasks:
  check:
    cmds:
      - npx remark . --quiet --frail
      - npx eslint . | tee eslint.log && npx tsx lint-formatter.ts eslint.log
      - npx tsc
      - npx madge --circular {{.TASKFILE_DIR}}/src/*
      - npx typedoc --emit none

  format:
    cmds:
      - npx remark . --quiet --frail --output
      - npx eslint --fix {{.TASKFILE_DIR}}
      - npx tsc
      - npx madge --circular {{.TASKFILE_DIR}}/src/*
      - npx typedoc --emit none

  build:
    cmds:
      - rm -Rf dist
      - npx tsc
      - node {{.TASKFILE_DIR}}/resources/post-build-script.js
