# Small memory optimizations from hiero-consensus-node
cache.warmThreads=1
blockStream.blockPeriod=200ms
blockStream.buffer.maxBlocks=5
blockStream.receiptEntriesBatchSize=256
blockStream.blockFileBufferOuterSizeKb=1024
blockStream.blockFileBufferInnerSizeKb=256
blockStream.blockFileBufferGzipSizeKb=128
hedera.prefetch.queueCapacity=1000
hedera.prefetch.threadPoolSize=1
hedera.recordStream.queueCapacity=100
hedera.recordStream.numOfBlockHashesInState=32
grpcUsageTracking.enabled=false
netty.bossThreads=1
netty.workerThreads=2
blockNode.connectionStallThresholdMillis=2000
