version: 3
includes:
  main:
    taskfile: ../Taskfile.examples.yml
    flatten: true
vars:
  solo_home_override_dir: "/home/gke1"
env:
  SOLO_NETWORK_SIZE: 4
  SOLO_NAMESPACE: solo-gke1
  SOLO_DEPLOYMENT: solo-deployment-gke1
  SOLO_CHART_VERSION: 0.42.3
  # CONSENSUS_NODE_VERSION: v0.58.0
  VALUES_FLAG: "--values-file {{.USER_WORKING_DIR}}/init-containers-values.yaml"
  SETTINGS_FLAG: "--settings-txt {{.USER_WORKING_DIR}}/settings.txt"
  SOLO_HOME: "{{.solo_home_override_dir}}"
  LOG4J2_FLAG: "--log4j2-xml {{.USER_WORKING_DIR}}/log4j2.xml"
  APPLICATION_PROPERTIES_FLAG: "--application-properties {{.USER_WORKING_DIR}}/application.properties"
  HEDERA_SERVICES_ROOT: "/home/gke1/workspaces/10nodes/hiero-consensus-node"
  LOCAL_BUILD_FLAG: "--local-build-path {{.HEDERA_SERVICES_ROOT}}/hedera-node/data"
  GENESIS_THROTTLES_FLAG: "--genesis-throttles-file {{.USER_WORKING_DIR}}/throttles.json"
  # SOLO_CHARTS_DIR_FLAG: "--chart-dir /Users/user/source/solo-charts/charts"
