downloadArtifactAction: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
downloadArtifactActionComment: v4.1.8
tests:
  # name: capitalized noun form
  # testFilePrefix: node-update # for node-update.test.mjs
  - name: Integration
    mochaPostfix: "'test/e2e/integration/**/*.ts'"

  - name: Standard
    mochaPostfix: "'test/e2e/**/*.ts' --ignore 'test/unit/**/*.ts' --ignore 'test/e2e/integration/**/*.ts' --ignore 'test/e2e/commands/mirror_node*.ts' --ignore 'test/e2e/commands/node*.ts' --ignore 'test/e2e/commands/separate_node*.ts' --ignore 'test/e2e/commands/relay*.ts'"
    timeout: 30000

  - name: Mirror Node
    mochaPostfix: "'test/e2e/commands/mirror_node.test.ts'"

  - name: Node PEM Stop
    mochaPostfix: "'test/e2e/commands/node_pem_stop.test.ts'"

  - name: Node PEM Kill
    mochaPostfix: "'test/e2e/commands/node_pem_kill.test.ts'"

  - name: Node Local Hedera
    mochaPostfix: "'test/e2e/commands/node_local_hedera.test.ts'"

  - name: Node Local PTT
    mochaPostfix: "'test/e2e/commands/node_local_ptt.test.ts'"

  - name: Node Add
    mochaPostfix: "'test/e2e/commands/node_add.test.ts'"

  - name: Node Add Local
    mochaPostfix: "'test/e2e/commands/node_add_local.test.ts'"

  - name: Node Add - Separate commands
    mochaPostfix: "'test/e2e/commands/separate_node_add.test.ts'"

  - name: Node Update
    mochaPostfix: "'test/e2e/commands/node_update.test.ts'"

  - name: Node Update - Separate commands
    mochaPostfix: "'test/e2e/commands/separate_node_update.test.ts'"

  - name: Node Delete
    mochaPostfix: "'test/e2e/commands/node_delete.test.ts'"

  - name: Node Delete - Separate commands
    mochaPostfix: "'test/e2e/commands/separate_node_delete.test.ts'"

  - name: Node Upgrade
    mochaPostfix: "'test/e2e/commands/node_upgrade.test.ts'"

  - name: Node Upgrade - Separate commands
    mochaPostfix: "'test/e2e/commands/separate_node_upgrade.test.ts'"

  - name: Relay
    mochaPostfix: "'test/e2e/commands/relay.test.ts'"
