downloadArtifactAction: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 
downloadArtifactActionComment: v4.1.8
tests:
  # name: capitalized noun form
  # testFilePrefix: node-update # for node-update.test.mjs
  - name: Standard
    mochaPostfix: "--ignore '.*\\/unit\\/.*' --ignore '.*\\/e2e\\/commands\\/mirror_node.*' --ignore '.*\\/e2e\\/commands\\/node.*' --ignore '.*\\/e2e\\/commands\\/separate_node.*' --ignore '.*\\/e2e\\/commands\\/relay.*'"
  - name: Mirror Node
    mochaPostfix: "--grep 'mirror_node\\.test\\.mjs'"
  - name: Node PEM Stop
    mochaPostfix: "--grep 'node_pem_stop\\.test\\.mjs'"
  - name: Node PEM Kill
    mochaPostfix: "--grep 'node_pem_kill\\.test\\.mjs'"
  - name: Node Local Build
    mochaPostfix: "--grep 'node_local.*\\.test\\.mjs'"
  - name: Node Add
    mochaPostfix: "--grep 'node_add.*\\.test\\.mjs'"
  - name: Node Add - Separate commands
    mochaPostfix: "--grep 'separate_node_add.*\\.test\\.mjs'"
  - name: Node Update
    mochaPostfix: "--grep 'node_update.*\\.test\\.mjs'"
  - name: Node Delete
    mochaPostfix: "--grep 'node_delete.*\\.test\\.mjs'"
  - name: Node Delete - Separate commands
    mochaPostfix: "--grep 'separate_node_delete.*\\.test\\.mjs'"
  - name: Node Upgrade
    mochaPostfix: "--grep 'node_upgrade.*\\.test\\.mjs'"
  - name: Relay
    mochaPostfix: "--grep 'relay\\.test\\.mjs'"