downloadArtifactAction: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 
downloadArtifactActionComment: v4.1.8
tests:
  # name: capitalized noun form
  # testFilePrefix: node-update # for node-update.test.mjs
  - name: Standard
    jestPostfix: --testPathIgnorePatterns=\".*/unit/.*\" --testPathIgnorePatterns=\".*/e2e/commands/mirror_node.*\" --testPathIgnorePatterns=\".*/e2e/commands/node.*\" --testPathIgnorePatterns=\".*/e2e/commands/relay.*\" 
  - name: Mirror Node
    jestPostfix: --testRegex=\".*\\/e2e\\/commands\\/mirror_node\\.test\\.mjs\"
  - name: Node PEM Stop
    jestPostfix: --testRegex=\".*\\/e2e\\/commands\\/node_pem_stop\\.test\\.mjs\" 
  - name: Node PEM Kill
    jestPostfix: --testRegex=\".*\\/e2e\\/commands\\/node_pem_kill\\.test\\.mjs\"
  - name: Node Local Build
    jestPostfix: --testRegex=\".*\\/e2e\\/commands\\/node_local.*\\.test\\.mjs\"
  - name: Node Add
    jestPostfix: --testRegex=\".*\\/e2e\\/commands\\/node_add.*\\.test\\.mjs\"
  - name: Node Add - Separate commands
    jestPostfix: --testRegex=\".*\\/e2e\\/commands\\/node_add_separate.*\\.test\\.mjs\"
  - name: Node Update
    jestPostfix: --testRegex=\".*\\/e2e\\/commands\\/node_update.*\\.test\\.mjs\"
  - name: Node Delete
    jestPostfix: --testRegex=\".*\\/e2e\\/commands\\/node_delete.*\\.test\\.mjs\"
  - name: Relay
    jestPostfix: --testRegex=\".*\\/e2e\\/commands\\/relay\\.test\\.mjs\"
