ingress:
  enabled: true
  hosts:
    - host: "explorer.solo.local"
      paths:
        - path: /
          pathType: Prefix
    - host: "mirror.solo.local"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ca-secret-hiero-explorer
      hosts:
        - '{{ index .Values.ingress.hosts 0 "host" }}'
