version: 3
includes:
  main:
    taskfile: ../Taskfile.examples.yml
    flatten: true
vars:
  solo_home_override_dir: "/Users/user/.solo-gke-test"
  use_port_forwards: "true"
env:
  SOLO_NETWORK_SIZE: 4
  SOLO_NAMESPACE: solo-gke-test
  SOLO_DEPLOYMENT: solo-deployment-gke-test
  # SOLO_CHART_VERSION: 0.39.0
  # CONSENSUS_NODE_VERSION: v0.58.0
  VALUES_FLAG: "--values-file {{.USER_WORKING_DIR}}/init-containers-values.yaml"
  SETTINGS_FLAG: "--settings-txt {{.USER_WORKING_DIR}}/settings.txt"
  # SOLO_HOME: "{{.solo_home_override_dir}}"
  LOG4J2_FLAG: "--log4j2-xml {{.USER_WORKING_DIR}}/log4j2.xml"
  APPLICATION_PROPERTIES_FLAG: "--application-properties {{.USER_WORKING_DIR}}/application.properties"
  HEDERA_SERVICES_ROOT: "/Users/user/source/hedera-services"
  #  LOCAL_BUILD_FLAG: "--local-build-path {{.HEDERA_SERVICES_ROOT}}/hedera-node/data"
  GENESIS_THROTTLES_FLAG: "--genesis-throttles-file {{.USER_WORKING_DIR}}/throttles.json"
  SOLO_CHARTS_DIR_FLAG: "-d /Users/user/source/solo-charts/charts"
  LOAD_BALANCER_FLAG: "--load-balancer true"
  ENABLE_EXPLORER_TLS_FLAG: "--enable-hedera-explorer-tls"
  TLS_CLUSTER_ISSUER_TYPE_FLAG: "--tls-cluster-issuer-type acme-staging"
  # CLUSTER_TLS_FLAGS: "--cert-manager --cert-manager-crds"
  NETWORK_DEPLOY_EXTRA_FLAGS: "--haproxy-ips node1=<ip-address>,node2=<ip-address>,node3=<ip-address>,node4=<ip-address> --pvcs"
  MIRROR_NODE_DEPLOY_EXTRA_FLAGS: "--values-file {{.USER_WORKING_DIR}}/mirror-and-explorer-values.yaml"
  RELAY_NODE_DEPLOY_EXTRA_FLAGS: "--values-file {{.USER_WORKING_DIR}}/relay-values.yaml"
