name: Feature Enhancement
description: Enhance an existing feature
title: "<Please write a brief description of the feature enhancement here>"
labels: ["Feature Enhancement", "Pending Triage"]
body:
  - type: textarea
    id: target-feature
    attributes:
      label: Feature to Enhance
      description: Which existing feature would you like to enhance?
      render: markdown
      placeholder: |
        _A clear and concise description of the feature you want to enhance._
    validations:
      required: true
  - type: textarea
    id: enhancement-description
    attributes:
      label: Requested Enhancement
      description: What would you like to enhance or change about this feature?
      render: markdown
      placeholder: |
        _A clear and concise description of what you want to happen._

        Note: Feature enhancements to integrate vendor specific cloud tools (e.g. awscli, gcloud-sdk, azure-cli) will likely be rejected as the Full Stack Testing (FST) Suite aims to be vendor agnostic.
    validations:
      required: true
  - type: textarea
    id: feature-justification
    attributes:
      label: Business Need
      description: Why is this needed?
      render: markdown
      placeholder: |
        _A clear and concise description of any alternative solutions or other features you've considered._
        
        Note: Please provide a clear and concise description of the business need for this enhancement. This will help us prioritize the feature request.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context or screenshots about the feature request here.
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
