version: 3
includes:
  main:
    taskfile: ../../Taskfile.yml
    flatten: true
vars:
  use_port_forwards: "true"

env:
  SOLO_NETWORK_SIZE: "1"
  SOLO_DEPLOYMENT: "solo-e2e"
  SOLO_NAMESPACE: "solo-e2e"
  SOLO_CLUSTER_NAME: "solo-e2e"

  NETWORK_DEPLOY_EXTRA_FLAGS: '--domain-names node1=node1'
  NODE_SETUP_EXTRA_FLAGS: '--domain-names node1=node1'
  MIRROR_NODE_DEPLOY_EXTRA_FLAGS: '--domain-name mirror-node'
  EXPLORER_DEPLOY_EXTRA_FLAGS: '--domain-name relay'
tasks:
  domain-name-test:
    desc: setups the network and tests it
    deps:
      - task: "init"
    cmds:
      - task: "default-with-mirror"
      - ( cd ../sdk-network-connection && npm i && node solo-network-connection.js )
