# Expose NodePort used by mirror-ingress-controller and explorer-ingress-controller
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31000
        hostPort: 31000
        protocol: TCP
      - containerPort: 31001
        hostPort: 31001
        protocol: TCP
      - containerPort: 32000
        hostPort: 32000
        protocol: TCP
      - containerPort: 32001
        hostPort: 32001
        protocol: TCP
