controller:
  service:
    type: NodePort
    httpPorts:
      - port: 9090
        targetPort: 9090
        nodePort: 32000
    httpsPorts:
      - port: 9443
        targetPort: 9443
        nodePort: 32001
  config:
    http-port: "9090"
    https-port: "9443"
    ssl-redirect: "false" # Allow HTTP traffic (disable forced redirect to HTTPS)
