controller:
  service:
    type: NodePort
    httpPorts:
      - port: 8080
        targetPort: 8080
    httpsPorts:
      - port: 8443
        targetPort: 8443
  config:
    http-port: "8080"   # HAProxy listens for HTTP on 8080
    https-port: "8443"  # HAProxy listens for HTTPS on 8443
    ssl-redirect: "false" # Allow HTTP traffic (disable forced redirect to HTTPS)
