import {container} from "tsyringe-neo";
import {SoloLogger} from "./logging.js";
import {PackageDownloader} from "./package_downloader.js";
import {Zippy} from "./zippy.js";
import {DependencyManager, HelmDependencyManager} from "./dependency_managers/index.js";
import * as constants from "./constants.js";
import {Helm} from "./helm.js";
import {ChartManager} from "./chart_manager.js";
import {ConfigManager} from "./config_manager.js";
import {K8} from "./k8.js";
import {AccountManager} from "./account_manager.js";
import {PlatformInstaller} from "./platform_installer.js";
import {KeyManager} from "./key_manager.js";
import {ProfileManager} from "./profile_manager.js";
import type {LeaseRenewalService} from "./lease/lease.js";
import {IntervalLeaseRenewalService} from "./lease/interval_lease_renewal.js";
import {LeaseManager} from "./lease/lease_manager.js";
import {CertificateManager} from "./certificate_manager.js";
import path from "path";
import {LocalConfig} from "./config/local_config.js";
import {RemoteConfigManager} from "./config/remote/remote_config_manager.js";

container.register<SoloLogger>(SoloLogger, {useValue: new SoloLogger('debug', false)});
container.register<PackageDownloader>(PackageDownloader, {useValue: new PackageDownloader()});
container.register<Zippy>(Zippy, {useValue: new Zippy()});
container.register<HelmDependencyManager>(HelmDependencyManager, {useValue: new HelmDependencyManager()});
container.register<DependencyManager>(DependencyManager, {useValue: new DependencyManager()});
container.register<Helm>(Helm, {useValue: new Helm()});
container.register<ChartManager>(ChartManager, {useValue: new ChartManager()});
container.register<ConfigManager>(ConfigManager, {useValue: new ConfigManager()});
container.register<K8>(K8, {useValue: new K8()});
container.register<AccountManager>(AccountManager, {useValue: new AccountManager()});
container.register<PlatformInstaller>(PlatformInstaller, {useValue: new PlatformInstaller()});
container.register<KeyManager>(KeyManager, {useValue: new KeyManager()});
container.register<ProfileManager>(ProfileManager, {useValue: new ProfileManager()});
container.register<IntervalLeaseRenewalService>(IntervalLeaseRenewalService, {useValue: new IntervalLeaseRenewalService()});
container.register<LeaseManager>(LeaseManager, {useValue: new LeaseManager(container.resolve(IntervalLeaseRenewalService))});
container.register<CertificateManager>(CertificateManager, {useValue: new CertificateManager()});

const localConfigPath = path.join(constants.SOLO_CACHE_DIR, constants.DEFAULT_LOCAL_CONFIG_FILE);
container.register<LocalConfig>(LocalConfig, {useValue: new LocalConfig(localConfigPath)});

const remoteConfigManager = container.resolve(RemoteConfigManager);
