version: 3
includes:
  main:
    taskfile: ../../ExamplesTasks.yml
    flatten: true
vars:
  solo_home_override_dir: "%HOME%/.solo"
env:
  SOLO_NETWORK_SIZE: 10
  SOLO_NAMESPACE: %SOLO_NAMESPACE%
  SOLO_CHART_VERSION: 0.36.3
  # CONSENSUS_NODE_VERSION: 0.0.0
  VALUES_FLAG: "--values-file {{.USER_WORKING_DIR}}/init-containers-values.yaml"
  SETTINGS_FLAG: "--settings-txt {{.USER_WORKING_DIR}}/settings.txt"
  SOLO_HOME: "{{.solo_home_override_dir}}"
  LOG4J2_FLAG: "--log4j2-xml {{.USER_WORKING_DIR}}/log4j2.xml"
  APPLICATION_PROPERTIES_FLAG: "--application-properties {{.USER_WORKING_DIR}}/application.properties"
  HEDERA_SERVICES_ROOT: "%HEDERA_SERVICES_ROOT%"
  LOCAL_BUILD_FLAG: "--local-build-path {{.HEDERA_SERVICES_ROOT}}/hedera-node/data"
