version: 3
output: prefixed
dotenv:
  - .env
silent: false

tasks:
  default:
    cmds:
      - task: "install"

  install:
    cmds:
      - task: "install:hugo"
      - task: "install:jsdoc"
      - task: "install:jsdoc-to-markdown"

  install:hugo:
    status:
      - command -v hugo
    cmds:
      - go install github.com/gohugoio/hugo@v0.124.1

  install:jsdoc:
    status:
      - command -v jsdoc
    cmds:
      - npm i -g jsdoc
      - jsdoc --version

  install:jsdoc-to-markdown:
    status:
      - command -v jsdoc2md
    cmds:
      - npm i -g jsdoc-to-markdown
      - jsdoc2md --version
