version: 3
includes:
  main:
    taskfile: ../Taskfile.examples.yml
    flatten: true
env:
  SOLO_NETWORK_SIZE: 10
  SOLO_NAMESPACE: solo-alex-kuzmin-n4
  SOLO_DEPLOYMENT: solo-deployment-alex-kuzmin-n4
  # SOLO_CHART_VERSION: 0.39.0
  # CONSENSUS_NODE_VERSION: v0.58.0
  VALUES_FLAG: "--values-file {{.USER_WORKING_DIR}}/init-containers-values.yaml"
  SETTINGS_FLAG: "--settings-txt {{.USER_WORKING_DIR}}/settings.txt"
  SOLO_HOME: "/Users/user/.solo-alex-kuzmin-n4"
  LOG4J2_FLAG: "--log4j2-xml {{.USER_WORKING_DIR}}/log4j2.xml"
  APPLICATION_PROPERTIES_FLAG: "--application-properties {{.USER_WORKING_DIR}}/application.properties"
  # HEDERA_SERVICES_ROOT: "/Users/user/source/hiero-consensus-node"
  # LOCAL_BUILD_FLAG: "--local-build-path {{.HEDERA_SERVICES_ROOT}}/hedera-node/data"
