##
# Copyright (C) 2023-2024 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "ZXC: Environment Variables"
# The purpose of this reusable workflow is to provide environment variables for use in re-usable workflows.

on:
  workflow_call:
    inputs:
      custom-job-label:
        description: "Custom Job Label:"
        type: string
        required: false
        default: "Set Environment Variables"
    outputs:
      e2e-integration-test-subdir:
        description: "E2E Integration Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_integration_test_subdir }}
      e2e-standard-test-subdir:
        description: "E2E Standard Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_standard_test_subdir }}
      e2e-mirror-node-test-subdir:
        description: "E2E Mirror Node Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_mirror_node_test_subdir }}
      e2e-node-pem-stop-test-subdir:
        description: "E2E Node PEM Stop Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_node_pem_stop_test_subdir }}
      e2e-node-pem-kill-test-subdir:
        description: "E2E Node PEM Kill Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_node_pem_kill_test_subdir }}
      e2e-node-local-hedera-test-subdir:
        description: "E2E Node Local Hedera Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_node_local_hedera_test_subdir }}
      e2e-node-local-ptt-test-subdir:
        description: "E2E Node Local PTT Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_node_local_ptt_test_subdir }}
      e2e-node-add-test-subdir:
        description: "E2E Node Add Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_node_add_test_subdir }}
      e2e-node-add-local-test-subdir:
        description: "E2E Node Add Local Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_node_add_local_test_subdir }}
      e2e-node-add-separate-commands-test-subdir:
        description: "E2E Node Add - Separate commands Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_node_add_separate_commands_test_subdir }}
      e2e-node-update-test-subdir:
        description: "E2E Node Update Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_node_update_test_subdir }}
      e2e-node-delete-test-subdir:
        description: "E2E Node Delete Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_node_delete_test_subdir }}
      e2e-node-delete-separate-commands-test-subdir:
        description: "E2E Node Delete - Separate commands Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_node_delete_separate_commands_test_subdir }}
      e2e-node-upgrade-test-subdir:
        description: "E2E Node Upgrade Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_node_upgrade_test_subdir }}
      e2e-relay-test-subdir:
        description: "E2E Relay Test Subdirectory"
        value: ${{ jobs.env-vars.outputs.e2e_relay_test_subdir }}
      e2e-integration-coverage-report:
        description: "E2E Integration Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_integration_coverage_report }}
      e2e-standard-coverage-report:
        description: "E2E Standard Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_standard_coverage_report }}
      e2e-mirror-node-coverage-report:
        description: "E2E Mirror Node Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_mirror_node_coverage_report }}
      e2e-node-pem-stop-coverage-report:
        description: "E2E Node PEM Stop Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_node_pem_stop_coverage_report }}
      e2e-node-pem-kill-coverage-report:
        description: "E2E Node PEM Kill Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_node_pem_kill_coverage_report }}
      e2e-node-local-hedera-coverage-report:
        description: "E2E Node Local Hedera Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_node_local_hedera_coverage_report }}
      e2e-node-local-ptt-coverage-report:
        description: "E2E Node Local PTT Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_node_local_ptt_coverage_report }}
      e2e-node-add-coverage-report:
        description: "E2E Node Add Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_node_add_coverage_report }}
      e2e-node-add-local-coverage-report:
        description: "E2E Node Add Local Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_node_add_local_coverage_report }}
      e2e-node-add-separate-commands-coverage-report:
        description: "E2E Node Add - Separate commands Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_node_add_separate_commands_coverage_report }}
      e2e-node-update-coverage-report:
        description: "E2E Node Update Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_node_update_coverage_report }}
      e2e-node-delete-coverage-report:
        description: "E2E Node Delete Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_node_delete_coverage_report }}
      e2e-node-delete-separate-commands-coverage-report:
        description: "E2E Node Delete - Separate commands Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_node_delete_separate_commands_coverage_report }}
      e2e-node-upgrade-coverage-report:
        description: "E2E Node Upgrade Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_node_upgrade_coverage_report }}
      e2e-relay-coverage-report:
        description: "E2E Relay Tests Coverage Report"
        value: ${{ jobs.env-vars.outputs.e2e_relay_coverage_report }}

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  env-vars:
    name: ${{ inputs.custom-job-label || 'Set Environment Variables' }}
    runs-on: solo-linux-medium
    outputs:
      e2e_integration_test_subdir: e2e-integration
      e2e_standard_test_subdir: e2e-standard
      e2e_mirror_node_test_subdir: e2e-mirror-node
      e2e_node_pem_stop_test_subdir: e2e-node-pem-stop
      e2e_node_pem_kill_test_subdir: e2e-node-pem-kill
      e2e_node_local_hedera_test_subdir: e2e-node-local-hedera
      e2e_node_local_ptt_test_subdir: e2e-node-local-ptt
      e2e_node_add_test_subdir: e2e-node-add
      e2e_node_add_local_test_subdir: e2e-node-add-local
      e2e_node_add_separate_commands_test_subdir: e2e-node-add-separate-commands
      e2e_node_update_test_subdir: e2e-node-update
      e2e_node_delete_test_subdir: e2e-node-delete
      e2e_node_delete_separate_commands_test_subdir: e2e-node-delete-separate-commands
      e2e_node_upgrade_test_subdir: e2e-node-upgrade
      e2e_relay_test_subdir: e2e-relay
      e2e_integration_coverage_report: "E2E Integration Tests Coverage Report"
      e2e_standard_coverage_report: "E2E Standard Tests Coverage Report"
      e2e_mirror_node_coverage_report: "E2E Mirror Node Tests Coverage Report"
      e2e_node_pem_stop_coverage_report: "E2E Node PEM Stop Tests Coverage Report"
      e2e_node_pem_kill_coverage_report: "E2E Node PEM Kill Tests Coverage Report"
      e2e_node_local_hedera_coverage_report: "E2E Node Local Hedera Tests Coverage Report"
      e2e_node_local_ptt_coverage_report: "E2E Node Local PTT Tests Coverage Report"
      e2e_node_add_coverage_report: "E2E Node Add Tests Coverage Report"
      e2e_node_add_local_coverage_report: "E2E Node Add Local Tests Coverage Report"
      e2e_node_add_separate_commands_coverage_report: "E2E Node Add - Separate commands Tests Coverage Report"
      e2e_node_update_coverage_report: "E2E Node Update Tests Coverage Report"
      e2e_node_delete_coverage_report: "E2E Node Delete Tests Coverage Report"
      e2e_node_delete_separate_commands_coverage_report: "E2E Node Delete - Separate commands Tests Coverage Report"
      e2e_node_upgrade_coverage_report: "E2E Node Upgrade Tests Coverage Report"
      e2e_relay_coverage_report: "E2E Relay Tests Coverage Report"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - run: echo "Exposing environment variables to reusable workflows"
