##
# Copyright (C) 2023-2024 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "ZXC: Code Analysis"
# The purpose of this reusable workflow is to perform static code analysis and code coverage reporting.
# This reusable component is called by the following workflows:
# - .github/workflows/flow-pull-request-checks.yaml
# - .github/workflows/flow-build-application.yaml
#
# This workflow is only run if the pull request is coming from the original repository and not a fork.

on:
  workflow_call:
    inputs:
      enable-codecov-analysis:
        description: "CodeCov Analysis Enabled"
        type: boolean
        required: false
        default: false
      enable-codacy-coverage:
        description: "Codacy Coverage Enabled"
        type: boolean
        required: false
        default: false
      enable-e2e-coverage-report:
        description: "E2E Coverage Report Enabled"
        type: boolean
        required: false
        default: false
      enable-snyk-scan:
        description: "Snyk Scan Enabled"
        type: boolean
        required: false
        default: false
      node-version:
        description: "NodeJS Version:"
        type: string
        required: false
        default: "20"
      custom-job-label:
        description: "Custom Job Label:"
        type: string
        required: false
        default: "Analyze"
      e2e-test-subdir:
        description: "E2E Test Subdirectory:"
        type: string
        required: false
        default: "e2e"
      e2e-mirror-node-test-subdir:
        description: "E2E Mirror Node Test Subdirectory:"
        type: string
        required: false
        default: "e2e-mirror-node"
      e2e-node-pem-stop-add-test-subdir:
        description: "E2E Node PEM Stop Add Test Subdirectory:"
        type: string
        required: false
        default: "e2e-node-pem-stop-add"
      e2e-node-pfx-kill-add-test-subdir:
        description: "E2E Node PFX Kill Add Test Subdirectory:"
        type: string
        required: false
        default: "e2e-node-pfx-kill-add"
      e2e-node-local-build-test-subdir:
        description: "E2E Node Local Build Test Subdirectory:"
        type: string
        required: false
        default: "e2e-node-local-build"
      e2e-relay-test-subdir:
        description: "E2E Relay Test Subdirectory:"
        type: string
        required: false
        default: "e2e-relay"
      e2e-coverage-report:
        description: "E2E Coverage Report:"
        type: string
        required: false
        default: "E2E Tests Coverage Report"
      e2e-mirror-node-coverage-report:
        description: "E2E Mirror Node Coverage Report:"
        type: string
        required: false
        default: "E2E Mirror Node Tests Coverage Report"
      e2e-node-pem-stop-add-coverage-report:
        description: "E2E Node PEM Stop Add Coverage Report:"
        type: string
        required: false
        default: "E2E Node PEM Stop Add Tests Coverage Report"
      e2e-node-pfx-kill-add-coverage-report:
        description: "E2E Node PFX Kill Add Coverage Report:"
        type: string
        required: false
        default: "E2E Node PFX Kill Add Tests Coverage Report"
      e2e-relay-coverage-report:
        description: "E2E Relay Coverage Report:"
        type: string
        required: false
        default: "E2E Relay Tests Coverage Report"
    secrets:
      snyk-token:
        description: "The Snyk access token is used by Snyk to analyze the code for vulnerabilities "
        required: false
      codecov-token:
        description: "The CodeCov access token is used by CodeCov.io to analyze the code coverage "
        required: false
      codacy-project-token:
        description: "The Codacy project token used to report code coverage."
        required: false

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  analyze:
    name: ${{ inputs.custom-job-label || 'Analyze' }}
    runs-on: [self-hosted, Linux, medium, ephemeral]
    steps:
      - name: Checkout Code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: ${{ inputs.enable-sonar-analysis && '0' || '' }}

      - name: Setup Node with Retry
        uses: Wandalen/wretry.action@6feedb7dedadeb826de0f45ff482b53b379a7844 # v3.5.0
        with:
          action: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
          with: |
            node-version: ${{ inputs.node-version }}
            cache: npm
          attempt_limit: 3
          attempt_delay: 5000

      - name: Download Unit Test Coverage Report
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        if: ${{ (inputs.enable-codecov-analysis || inputs.enable-codacy-coverage) && !cancelled() && !failure() }}
        with:
          name: Unit Test Coverage Report
          path: 'coverage/unit'

      - name: Download E2E Coverage Report
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        if: ${{ (inputs.enable-codecov-analysis || inputs.enable-codacy-coverage) && inputs.enable-e2e-coverage-report && !cancelled() && !failure() }}
        with:
          name: ${{ inputs.e2e-coverage-report }}
          path: 'coverage/${{ inputs.e2e-test-subdir }}'

      - name: Download E2E Mirror Node Coverage Report
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        if: ${{ (inputs.enable-codecov-analysis || inputs.enable-codacy-coverage) && inputs.enable-e2e-coverage-report && !cancelled() && !failure() }}
        with:
          name: ${{ inputs.e2e-mirror-node-coverage-report }}
          path: 'coverage/${{ inputs.e2e-mirror-node-test-subdir }}'

      - name: Download E2E Node PEM Stop Add Coverage Report
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        if: ${{ (inputs.enable-codecov-analysis || inputs.enable-codacy-coverage) && inputs.enable-e2e-coverage-report && !cancelled() && !failure() }}
        with:
          name: ${{ inputs.e2e-node-pem-stop-add-coverage-report }}
          path: 'coverage/${{ inputs.e2e-node-pem-stop-add-test-subdir }}'

      - name: Download E2E Node PFX Kill Add Coverage Report
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        if: ${{ (inputs.enable-codecov-analysis || inputs.enable-codacy-coverage) && inputs.enable-e2e-coverage-report && !cancelled() && !failure() }}
        with:
          name: ${{ inputs.e2e-node-pfx-kill-add-coverage-report }}
          path: 'coverage/${{ inputs.e2e-node-pfx-kill-add-test-subdir }}'

      - name: Download E2E Relay Coverage Report
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        if: ${{ (inputs.enable-codecov-analysis || inputs.enable-codacy-coverage) && inputs.enable-e2e-coverage-report && !cancelled() && !failure() }}
        with:
          name: ${{ inputs.e2e-relay-coverage-report }}
          path: 'coverage/${{ inputs.e2e-relay-test-subdir }}'

      - name: Download E2E Local Build Coverage Report
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        if: ${{ (inputs.enable-codecov-analysis || inputs.enable-codacy-coverage) && inputs.enable-e2e-coverage-report && !cancelled() && !failure() }}
        with:
          name: ${{ inputs.e2e-local-build-test-report }}
          path: 'coverage/${{ inputs.e2e-local-build-test-subdir }}'

      - name: Publish To Codecov
        uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4.3.1
        if: ${{ inputs.enable-codecov-analysis && !cancelled() && !failure() }}
        env:
          CODECOV_TOKEN: ${{ secrets.codecov-token }}
        with:
          verbose: true
          directory: 'coverage'

      - name: Publish to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.codacy-project-token }}
        if: ${{ inputs.enable-codacy-coverage && !cancelled() && !failure() }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Javascript $(find . -name 'lcov.info' -printf '-r %p ')

      - name: Setup Snyk
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        if: ${{ inputs.enable-snyk-scan && !cancelled() && !failure() }}
        run: npm install -g snyk snyk-to-html @wcj/html-to-markdown-cli

      - name: Snyk Scan
        id: snyk
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        if: ${{ inputs.enable-snyk-scan && !cancelled() && !failure() }}
        run: snyk test --org=release-engineering-N6EoZVZn3jw4qNuVkiG5Qs --all-projects --severity-threshold=high --json-file-output=snyk-test.json

      - name: Snyk Code
        id: snyk-code
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        if: ${{ inputs.enable-snyk-scan && !cancelled() && !failure() }}
        run: snyk code test --org=release-engineering-N6EoZVZn3jw4qNuVkiG5Qs --severity-threshold=high --json-file-output=snyk-code.json

      - name: Publish Snyk Results
        if: ${{ inputs.enable-snyk-scan && !cancelled() && !failure() }}
        run: |
          if [[ -f "snyk-test.json" && -n "$(cat snyk-test.json | tr -d '[:space:]')" ]]; then
            snyk-to-html -i snyk-test.json -o snyk-test.html --summary
            html-to-markdown snyk-test.html -o snyk
            cat snyk/snyk-test.html.md >> $GITHUB_STEP_SUMMARY
          fi

      - name: Publish Snyk Code Results
        if: ${{ inputs.enable-snyk-scan && !cancelled() && !failure() }}
        run: |
          if [[ -f "snyk-code.json" && -n "$(cat snyk-code.json | tr -d '[:space:]')" ]]; then
            snyk-to-html -i snyk-code.json -o snyk-code.html --summary
            html-to-markdown snyk-code.html -o snyk
            cat snyk/snyk-code.html.md >> $GITHUB_STEP_SUMMARY
          fi

      - name: Check Snyk Files
        if: ${{ always() }}
        run: |
          echo "::group::Snyk File List"
            ls -lah snyk* || true
          echo "::endgroup::"
          echo "::group::Snyk Test Contents"
            cat snyk-test.json || true
          echo "::endgroup::"
          echo "::group::Snyk Code Contents"
            cat snyk-code.json || true
          echo "::endgroup::"

      - name: Publish Snyk Reports
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: ${{ inputs.enable-snyk-scan && !cancelled() && !failure() }}
        with:
          name: Snyk Reports
          path: |
            snyk-*.html
            snyk-*.json
